### ISSUE TITLE
Determine genesis block message

### ISSUE THREAD

**Issue by macterra** [cryptotechguru/tesseract-core#3]
Currently inherited from fork:
```
WSJ - 03/Jan/2018 - Billionaire Wagers Millions On Bitcoin
```

**Comment by Flaxscrip** [comment]
A visit to today's [NYT.com](https://www.nytimes.com/2019/04/30/us/politics/trump-infrastructure-plan.html) informs us that "Trump and Democrats Agree to Pursue $2 Trillion Infrastructure Plan". 

It's amazing how these organizations find ways to agree with one another when it comes to spending other people's money. Of course, this "infrastructure plan" completely misses the mark on the type of infrastructure that communities need in order to survive the realities of global competition.

**Comment by macterra** [comment]
Not bad. I think there may be a limit on number of characters, I'll investigate.

Feel free to propose in the [multi-vote](https://github.com/cryptotechguru/Cryptonomicon/issues/34) discussion.

**Comment by macterra** [comment]
A Declaration of the Independence of Cyberspace:

[ipfs://QmaVyAGXU4J5DjMZDK88F9S24rCVtS6dXfu8Xfvt35vL2W/cyberspace-independence/pub/](https://ipfs.io/ipfs/QmaVyAGXU4J5DjMZDK88F9S24rCVtS6dXfu8Xfvt35vL2W/cyberspace-independence/pub/)
